config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users, controllers: { 
    registrations: "registrations",
    sessions: "sessions"       
  }

  resources :messages do
    collection do
      get 'refresh'
    end
  end
  post 'tags' => 'messages#tags'
  get  'followed' => 'messages#followed'
  get  'follow' => 'followings#follow' do
    resource :user
  end
  delete 'unfollow' => 'followings#unfollow' do
    resource :user
  end
  root 'welcome#index'
end

app/models/followings.rb
class Followings < ActiveRecord::Base
	belongs_to :user
  	belongs_to :follower, :class_name => 'User'
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates :content, presence: true
		
	belongs_to :user
	has_many :taggeds
	has_many :tags, through: :taggeds
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	validates :tag, presence: true, uniqueness: true

	has_many :taggeds
	has_many :messages, through: :taggeds

	def self.scan message
		content = message.content
		index = 0
		hashtags = content.scan(/(?:\s|^)(?:#(?!(?:\d+|\w+?_|_\w+?)(?:\s|$)))(\w+)(?=\s|$)/i).map{|x| x[0]}
		hashtags.each do|hashtag|
			tag = Tag.find_or_create_by(tag: hashtag)
			tag.save

			tagged = Tagged.new(tag_id: tag.id, message_id: message.id)
			tagged.save
		end
	end
end

app/models/tagged.rb
class Tagged < ActiveRecord::Base
	validates :tag_id, presence: true
	validates :message_id, presence: true

	belongs_to :tag
	belongs_to :message
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   	has_many :messages
   	has_many :followers, :class_name => 'Followings', :foreign_key => 'user_id'
  	has_many :following, :class_name => 'Followings', :foreign_key => 'follower_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
	def follow
		user = params[:user]
		followings = Followings.new(user_id: user, follower_id: current_user.id)
		if followings.save
			redirect_to followed_path
		else
			flash[:notice] = "Failed"
			redirect_to root_path
		end
	end

	def unfollow
		user = params[:user]
		followings = Followings.find_by(user_id: user, follower_id: current_user.id)
		followings.destroy
		redirect_to followed_path
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :new_message, only: [:index, :tags, :followed]

	def index
		@messages = Message.all.order("id DESC")
	end

	def create
		@message = current_user.messages.build(params.require(:message).permit(:content))
		if @message.save
			Tag.scan(@message)
			respond_to do |format|
				format.html { redirect_to messages_path }
			end
		else
			# didnt work tell user
			flash[:notice] = "Failed"
			redirect_to messages_path
		end
	end

	def tags
		tagStrings = params[:tags][:tags]
		puts tagStrings.inspect
		@messages = tags_messages tagStrings
	end

	def followed
		@messages = followed_messages
		puts current_user.following.inspect
	end

	def destroy
		@message = Message.find(params[:id])
		@message.destroy
		redirect_to messages_path
	end

	def refresh
		page = request.headers["Referer"].split('/')[-1]
		case page
		when "followed"
			@messages = followed_messages
		when "tags"
			@messages = tags_messages params[:tags].gsub('+', ' ')
		else
			@messages = Message.all
		end
		last_id = params[:last_id]
		if @messages.instance_of? Array
			@messages = @messages.sort! { |a,b| b.id <=> a.id }
			@messages.delete_if do |message|
				if message.id <= last_id.to_i
					true
				end
			end
		else
			@messages = @messages.where("id > ?", last_id).order("id DESC")
		end
		respond_to do |format|
			format.js
		end
	end

	private

		def new_message
			@message = Message.new
		end

		def followed_messages
			messagesArray = []
			followings = current_user.following
			followings.each do |following|
				messagesArray << following.user.messages
			end
			if messagesArray.count > 0
				@messages = messagesArray[0]
				(1..(messagesArray.count-1)).each do |i|
					@messages = (@messages + messagesArray[i])
				end
				if messagesArray.count > 1
					@messages = @messages.sort! { |a,b| b.id <=> a.id }
				else
					@messages = @messages.order("id DESC")
				end
			else
				@messages = nil
			end
			@messages
		end

		def tags_messages tagStrings
			
			messagesArray = []
			puts "tagStrings: "+ tagStrings.inspect
			tagStrings.split(' ').each do |tagString|
				tag = Tag.find_or_create_by(tag: tagString)
				if !tag.nil?
					@messages = tag.messages
					messagesArray << @messages
				end
			end

			if messagesArray.count > 0
				@messages = messagesArray[0]
				(1..(messagesArray.count-1)).each do |i|
					@messages = (@messages & messagesArray[i])
				end
				if messagesArray.count > 1
					@messages = @messages.sort! { |a,b| b.id <=> a.id }
				else	
					@messages = @messages.order("id DESC")
				end
			else
				@messages = nil
			end
			@messages
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/messages' # Or :prefix_to_your_route
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected	

  def after_sign_in_path_for(resource)
    '/messages' # Or :prefix_to_your_route
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/views/layouts/_devise.html.erb
		<div class="deviseMessage">
		   <p class="notice"><%= notice %></p>
		   <p class="alert"><%= alert %></p>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hermes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<% if user_signed_in? %>
				<%= link_to "Hermes", messages_path, class: 'navbar-brand' %>
				<% else %>
				<%= link_to "Hermes", root_path, class: 'navbar-brand' %>
				<% end %>
			</div>
			<ul class="nav navbar-nav">
				<% if user_signed_in? %>
				<li><%= link_to "Followed", followed_path %></li>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li><%= link_to "Log In", user_session_path %> </li>
				<li><%= link_to "Sign Up", new_user_registration_path %> </li>
				<% end %>
			</ul>
			<% if user_signed_in? %>
			<%= simple_form_for :tags, url: tags_path, html: { class: "navbar-form navbar-right"} do |f| %>
  			<div class="form-group">
  				<%= f.input :tags, as: :string, label: false, class: "form-control" %>
  			</div>
  			<%= f.submit "Search", class: "btn btn-default" %>
			<% end %>
			<% end %>
		</div>
	</div>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/messages/_form.html.erb
<% if user_signed_in? %>
	<div class="messenger">
	<%= simple_form_for @message do |f| %>
		<%= f.input :content, label: false, placeholder: "Write your message...", input_html: { class: "myInput" } %>
		<%= f.button :submit, "Send" %>
	<% end %>
	</div>
<% end %>

app/views/messages/_messagesContainer.html.erb
<% if @messages.nil? %>
	<% if !@tagStrings.blank? %>
	<p>No messages with tag: <%= @tagStrings %></p>
	<% end %>
<% elsif !@messages.empty? %>
	<%= javascript_tag do %>
	var last_id = <%=j @messages.first.id.to_s %>;
	<% end %>
	<% @messages.each do |message| %>
	<% if request.original_url.include? 'refresh' %>
	<div class="message col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2 newMessage" data-message-id=<%= message.id %>>
	<% else %>
	<div class="message col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2" data-message-id=<%= message.id %>>	
	<% end %>
		<div class="massageAutor col-xs-8 col-md-10"><%= message.user.email %></div>
		<div class="posted col-xs-4 col-md-2"><%= time_ago_in_words(message.created_at) %></div>
		<div class="messageContent col-xs-12 col-md-12">
		<%= message.content %>
		</div>
		<% if user_signed_in? %>
		<div class="actions col-xs-12 col-md-12">
			
			<% if current_user.id == message.user_id %>
			<%= link_to message_path(message.id), method: :delete do %>
			<span class="glyphicon glyphicon-remove"></span>
			<% end %>
			<% elsif current_user.following.where(follower_id: current_user.id, user_id: message.user.id).empty? %>
			<%= link_to "Follow", follow_path(user: message.user) %>
			<% else %>
			<%= link_to "Unfullow", unfollow_path(user: message.user), method: :delete %>
			<% end %>
		</div>
		<% end %>
	</div>
	<% end %>
<% end %>

app/views/messages/followed.html.erb
<%= render 'form' %>
<div class="messages row">
<%= render 'messagesContainer' %>
</div>

app/views/messages/index.html.erb
<%= javascript_tag do %>
var last_id = <%=j @messages.first.id.to_s %>;
<% end %>
<%= render 'form' %>
<div class="messages row">
<%= render 'messagesContainer' %>
</div>

app/views/messages/refresh.js.erb
html = "<%=j render 'messagesContainer', messages: @messages %>"

if (html.length > 0) {
	$('.messages').prepend(html).hide().fadeIn('slow');
}

app/views/messages/tags.html.erb
<%= render 'form' %>
<h1><%= @messages.count %> search result for tags: <%= params[:tags][:tags] %></h1>
<%= javascript_tag do %>
var tags = <%= raw params[:tags][:tags].to_json %>;
<% end %>
<div class="messages row">
<%= render 'messagesContainer' %>
</div>

app/views/welcome/index.html.erb
<div class="row">
<div class="col-md-12">
	<div class="col-md-offset-1 col-md-8 title"><h1>Hermes - the godlike messanger!</h2></div>
	<div class="col-md-6">
	<div class="feature"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Free registration. Always.</div><div class="feature"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Sign Up and share messeges with the community.</div>
	<div class="feature"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Tag your messages and easily search for the topics of interest.</div>
	<div class="feature"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Follow and be followed by other users.</div>
	</div>
</div>

<%= render 'devise/shared/form' %>
</div>